### ISSUE TITLE
SOL is not rendering on the page in IE

### ISSUE THREAD

**Issue by bobtsang** [pbauerochse/searchable-option-list#15]
Hi,

I find sol really cool and it totally works fine in Chrome.

However, when I open the [sol example page](http://pbauerochse.github.io/searchable-option-list/examples.html) with IE 11, the first few examples are not rendering. 

Same thing happened in my own project using sol and th error console is attached below.
![image](https://cloud.githubusercontent.com/assets/8850044/11461198/4ff155ec-96cc-11e5-917a-920e6d5b8ccd.png)

**Comment by pbauerochse** [comment]
Hi @bobtsang ,

thanks for your kind words. I must admit, that I'm not a big fan of IE and therefore am very lazy in testing it with IE. I also have very limited access to IE since my development system is not running windows.

Luckily @implico provided a fix for the issue and I just merged his changes. So the IE error should be fixed now. Can you check again?

Thanks for your patience and once again @implico thanks for providing a fix

Cheers to bot of you

Patrick

**Comment by eskimoblood** [comment]
So is this issue fixed in the latest version?

**Comment by pbauerochse** [comment]
@eskimoblood it should be. I could not verify it though since I don't have access to a windows machine right now.

**Comment by lucaferri** [comment]
@pbauerochse my client says it now works on windows IE/Edge.

**Comment by pbauerochse** [comment]
Thanks for the info
