### ISSUE TITLE
searchable-option-list : select box will take time to load when loading the page

### ISSUE THREAD

**Issue by hasif4157** [pbauerochse/searchable-option-list#38]
Firstly i would like to say thank you to ur team for this wonderful plugin......

When em using if i reload the page , multi select box will take time to load(it is showing all inner body i mean it is collapsing the box). Can u please assist me how i can overcome from this issue.

**Comment by pbauerochse** [comment]
Hi @hasif4157,

I'm not quite sure I understand the issue. Could you provide some screenshots displaying the problem?

Cheers

**Comment by hasif4157** [comment]
![beforeloading](https://cloud.githubusercontent.com/assets/19643132/15737525/8002a4d4-28b7-11e6-870b-fcbdca24f93f.png)
![afterpageload](https://cloud.githubusercontent.com/assets/19643132/15737532/8c77b114-28b7-11e6-8da9-e480ace6e0ff.png)

In first image beforeloading.png.......... when page loading multiselect box will collapse for few seconds ....... after few seconds will get the multiselect box (afterloading.png)

how can we solve this loading issue with ur searchable plugin?????

**Comment by pbauerochse** [comment]
Hi @hasif4157,

thanks for the screenshots. I have seen this problem before, especially when the data is really large. Sol should render the html elements before the data is being processed. This strangely does not seem to be working in your case.

Could you please provide me the following details:

- Which browser and what version are you using?
- Are there more than those four SOL containers on that page?
- How many items does each of the containers (approx.) contain? >100? >1000? >10000? or even more?

**Comment by hasif4157** [comment]
thanks for your response.....

Here all my details :
1)Google Chrome  Version 50.0.2661.102 m

2)Only four SOL container on that page....... remaining are simple default select box.

3)<100

I think i have met all your details.

Thank you again.

**Comment by hasif4157** [comment]
Hi......

Is thr any solution for my query......?


Can anyone help me out ......????

**Comment by hasif4157** [comment]
thanks for your response.....

Here all my details :
1)Google Chrome Version 50.0.2661.102 m

2)Only four SOL container on that page....... remaining are simple default
select box.

3)<100

I think i have met all your details.

Thank you again.

**Comment by pbauerochse** [comment]
Those boxes are the original select fields from which the SOL elements get created. So at the moment  you are seeing those boxes SOL is not properly initialized yet. This is most propably because the SOL script is not fully loaded yet or you are initializing the sol elements very late in the page rendering process.

It's hard to tell without seeing your markup. Would you be willing to attach an example file so I could investigate a bit further?

Cheers

**Comment by hasif4157** [comment]
yeah sure.....

**Comment by hasif4157** [comment]
[tester.zip](https://github.com/pbauerochse/searchable-option-list/files/311453/tester.zip)

Hi,
Please find uploaded file......... please check if i open index page on loading sol container will destructive.

**Comment by hasif4157** [comment]
Hi,
Please find attached file......... please check if i open index page on
loading sol container will collapse .

**Comment by pbauerochse** [comment]
Hi @hasif4157 ,

thanks for the example. As I suspected the problem is not SOL itself but the time when it is being initialized. Your browser has already rendered the original select elements before he gets to the point, where you tell him to initialize SOL. Unfortunately there is little possibilities to speed this up as the rendering of the SOL elements is taking place in JavaScript once the page has been loaded.

Here are a few things you could do to prevent the original selects from showing up:

1) include the sol.js already in the head section of your html. This could speed up the initialization
2) Hide your select elements when the page is being loaded. Either by doing `visibility:hidden` or `display:none`. That way your original select elements won't show up when the page is loaded. Once they are initialized by SOL, they will reappear
3) Or instead of hiding, you could style them the same way you styled the SOL container (giving them the same appearance via CSS so the user won't notice when they have been replaced by SOL)

I also noticed, that you include various versions of jQuery in your example. Maybe you could get rid of any unneccessary libraries so the page loading gets another performance boost.

Let me know if any of these hints helped you.

Cheers

**Comment by hasif4157** [comment]
Thanks for your quick response........

ill try given hint and get back to you

**Comment by hasif4157** [comment]
Hi...

I put style="display:none;" in 4 sol container.......it is really awesome it is working fine.....................

Thanks for your help. I really appreciate your hard work on making this wonderful plugin.

Thank you very much

**Comment by pbauerochse** [comment]
I'm glad I could help.

Cheers

**Comment by PreetiPeshwani** [comment]
Hello,

I have 4 SOLs.All are depending on each other.
Initially they all have all data,but after selection from first SOL they will have the filtered data.
For the second SOL I have more data to display so it when I am dynamically adding the options,It shows me "Still loading data...".

Can you please help me to solve this issue?

Attaching the screenshot.
![screenshot_2018 06 19_18 37 52](https://user-images.githubusercontent.com/13138632/41601134-3ada9fc0-73f5-11e8-9585-f7ec083cd9a2.png)
 

Thanks!
